 /********************************************************************
 * File Name:ultrasonic.c
 *
 * Model:-Source File of ultrasonic_sensor Driver
 *
 * Created on:10/10/2022
 *
 * Description:-ultrasonic_sensor to calculate the distance
 *
 * Author:Mohammed Sayed Shaaban
 ********************************************************************/
#include "gpio.h"
#include "ultrasonic.h"
#include "icu.h"
#include <util/delay.h>

#define F_CPU        8000000UL       /*to use the delay function*/
/****************************************************************************
 *                        Private prototypes
 ***************************************************************************/
/* Function_Name:Ultrasonic_Trigger
*
* Description:
*
* Send the Trigger pulse to the ultrasonic.
*
*/
static void ULTRASONIC_trigger(void);

/* Function_Name:Ultrasonic_Trigger
*
* Description:
*
➢ This is the call back function called by the ICU driver.

➢ This is used to calculate the high time (pulse time) generated by
the ultrasonic sensor
*
*/
static void ULTRASONIC_edgeProcessing(void);
/***************************************************************************
 *                            Global Variables
 ***************************************************************************/
extern uint8 g_edgcount;        /*global variable to hold the count of edges*/
uint16 g_PeriodTime=0;         /*to hold the time */
/*
 * Function_Name:Ultrasonic_init
 *
 * Description:
 *
 * 1-setup the Ultrasonic sensor
 *
 * 2- Setup the direction for the trigger pin as output pin.
 *
 */
void ULTRASONIC_init(void){
	/*config the ICU_MODEL  as Required*/
	ICU_Config Icu_Conf;
	Icu_Conf.clock=F_CPU_8;
	Icu_Conf.edg=rising;
	ICU_init(&Icu_Conf);
	Timer1_setCallBack(ULTRASONIC_edgeProcessing);
	/*setup the Pin Trigger as Ouput pin*/
	GPIO_setupPinDirection(ULTRASONIC_TRIGGER_PORT_ID ,ULTRASONIC_TRIGGER_PIN_ID, PIN_OUTPUT);

}

/* Function_Name:Ultrasonic_Trigger
*
* Description:
*
* Send the Trigger pulse to the ultrasoni.
*
*/
static void ULTRASONIC_trigger(void){
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT_ID ,ULTRASONIC_TRIGGER_PIN_ID, LOGIC_HIGH);
	_delay_us(15);
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT_ID ,ULTRASONIC_TRIGGER_PIN_ID, LOGIC_LOW);
}

/* Function_Name:Ultrasonic_readDistance
*
* Description:
*
*➢ Send the trigger pulse by using Ultrasonic_Trigger function.
*➢
*➢  Start the measurements by the ICU from this moment
*
*/
uint16 ULTRASONIC_readDistance(void){
	uint16 distance;
	ULTRASONIC_trigger();          /*to trigger the sensor to be ready*/
	distance =(g_PeriodTime/58.8); /*the equation to get the distance from the time*/
	return distance;
}

/* Function_Name:Ultrasonic_Trigger
*
* Description:
*
➢ This is the call back function called by the ICU driver.

➢ This is used to calculate the high time (pulse time) generated by
the ultrasonic sensor
*
*/
static void ULTRASONIC_edgeProcessing(void){
	g_edgcount++;
	if(g_edgcount==1){
		ICU_setEdge(falling); /*to set the edge with falling edge*/
		ICU_clearTimer();  /*to count time from there*/
	}
	else if(g_edgcount==2){
		g_PeriodTime= ICU_getInputCapture();
		ICU_setEdge(rising);    /*to set the edge with rising edge*/
		ICU_clearTimer();
	}

}
